### ISSUE TITLE
can't start the agent service

### ISSUE THREAD

**Issue by yln209** [AutohomeRadar/Windows-Agent#2]
install pass:
D:\Program Files\Open-falcon>python agent.py install
Installing service OpenFalconAgent
Service installed

can 't startup the agent service:
D:\Program Files\Open-falcon>python agent.py start
Starting service OpenFalconAgent
Error starting service: 服务没有及时响应启动或控制请求。

**Comment by ninjadq** [comment]
if your logged user not the author of python， you may need add environment variable 

```
set PATH=%PATH%;C:\Python27;C:\Python27\Lib\site-packages\pywin32_system32
```

**Comment by yln209** [comment]
thanks. 
i install the python and agent with administrator.  
i add "C:\Python27\Lib\site-packages\pywin32_system32" to the %PATH%  ，another problem acur

 can‘t startup the service with err：
Python could not import the service's module 
Traceback (most recent call last):
  File "C:\Windows-Agent\agent.py", line 21, in <module>
    class AppServerSvc (win32serviceutil.ServiceFramework):
  File "C:\Windows-Agent\agent.py", line 21, in <module>
    class AppServerSvc (win32serviceutil.ServiceFramework):
  File "C:\Python27\lib\bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "C:\Python27\lib\bdb.py", line 68, in dispatch_line
    if self.quitting: raise BdbQuit
BdbQuit 
%2: %3

**Comment by yln209** [comment]
hi, pls ignore.
i found the reason.

**Comment by yu351317720** [comment]
PS D:\用户目录\desktop\v4\Windows-Agent>  python agent.py start
Starting service OpenFalconAgent
PS D:\用户目录\desktop\v4\Windows-Agent> echo $?
True
有人吗？请问我执行了上面命令显示无问题，但是实际OpenFalconAgent 服务并没有启动起来
