### ISSUE TITLE
python agent.py start 启动时 提示服务没有及时响应启动或控制请求

### ISSUE THREAD

**Issue by xiaohei417** [AutohomeRadar/Windows-Agent#6]

**Comment by luck-xiaohei** [comment]
![image](https://user-images.githubusercontent.com/41576095/62536808-839e6a80-b881-11e9-96cf-aece7727739b.png)

**Comment by luck-xiaohei** [comment]
![image](https://user-images.githubusercontent.com/41576095/62536825-8d27d280-b881-11e9-8890-1bad1bc8fbb2.png)

**Comment by xiaohei417** [comment]
![image](https://user-images.githubusercontent.com/41576095/62537361-ca409480-b882-11e9-8bc4-c184bbdfa68b.png)

**Comment by ninjadq** [comment]
hi, can you check the environment variable?

**Comment by CCColby** [comment]
I also get this error.

**Comment by CCColby** [comment]
> _No description provided._

have you slove this problem?

**Comment by ninjadq** [comment]
Mostly this is caused by wrong env variable settings.

**Comment by CCColby** [comment]
> Mostly this is caused by wrong env variable settings.

I have installed all packages.which variable settings need to do.

**Comment by xiaohei417** [comment]
> > 通常，这是由错误的环境变量设置引起的。
> 
> 我已经安装了所有软件包。需要进行变量设置。

我没有解决该问题
